### SERVER CONFIG
server:
  port: 8080

spring:
  ### DB CONFIG
  jpa:
    hibernate.ddl-auto: none
    show-sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/clinic_db
    username: root
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver

  ### FLYWAY CONFIG
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

### SECURITY CONFIG
#  security:
#    user:
#      name: admin
#      password: pass

### LOGGING CONFIG

logging:
  level:
    root: info
  file:
    name: log/clinics_api.log
  logback:
    rollingpolicy:
      max-history: 30
      max-file-size: 1GB

