spring:
  jpa:
    hibernate.ddl-auto: none
    show-sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/clinic_db
    username: root
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level: info
  file:
    name: log/clinics_api.log
  logback:
    rollingpolicy:
      max-history: 30
      max-file-size: 1GB
